### ISSUE TITLE
Roadmap for new version

### ISSUE THREAD

**Issue by Progi1984** [PHPOffice/PHPWord#2268]
- [x] Migration to Github Actions from Travis CI
- [x] Support for recents versions of PHP and remove support for PHP < 7.1
- [x] Add PHPStan
- [x] Add PHPCSFixer
- [x] Use Coveralls for replacing Scrutinizer
- [x] Remove all deprecated
- [x] Migration documentation to Markdown (@mkdocs)
- [x] Migrate from PHPExcel to PhpSpreadsheet
- [ ] Define new exceptions for each error
- [ ] Add declare strict_types for each file
- [x] Upgrade major version of PHPOffice\Common

Inspired from PHPOffice/PHPPresentation#634

**Comment by PowerKiKi** [comment]
I marked PHPStan as added, following #2405
