### ISSUE TITLE
Roadmap for v2.0

### ISSUE THREAD

**Issue by Progi1984** [PHPOffice/PHPWord#2544]
- Add declare strict_types for each file & Type each method
  - [ ]  `src/PhpWord/Collection`
  - [ ]  `src/PhpWord/ComplexType`
  - [ ]  `src/PhpWord/Element`
  - [ ]  `src/PhpWord/Escaper`
  - [ ]  `src/PhpWord/Exception`
  - [ ]  `src/PhpWord/Metadata`
  - [ ]  `src/PhpWord/Reader`
  - [ ]  `src/PhpWord/Shared`
  - [ ]  `src/PhpWord/SimpleType`
  - [ ]  `src/PhpWord/Style`
  - [ ]  `src/PhpWord/Writer`
  - [ ]  `src/PhpWord/*`

- PR Milestoned 2.0 : https://github.com/PHPOffice/PHPWord/pulls?q=is%3Aopen+is%3Apr+milestone%3A2.0.0
- Issues Milestoned 2.0 : https://github.com/PHPOffice/PHPWord/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0.0

**Comment by hazington** [comment]
If you want, I can help you to convert phpword to a strict library that only supports PHP 8.3 and later. I would also change the array-based element config to an object-based config that has factory methods like fromArray() to ensure that the "old way" still works. 

I've created a HTML2Word Library that is currently only used internally in production. I could add this to the source code of phpword. I think that my implementation is more stable, faster and feature rich. 

I could start with my contribution in September 2026. I would try to keep breaking changes as minimal as possible. But for a fully strict typed and non "magic" implementation this cannot be guaranteed.
