### ISSUE TITLE
Mission to 1.0.0

### ISSUE THREAD

**Issue by Progi1984** [PHPOffice/PHPWord#81]
- [x] Documentation of the project with ReadTheDocs (#43 / #82)
- [x] Writers
  - [x] HTML Writer (#67)
  - [x] PDF Writer (#68)
- [x] Readers
  - [x] DOCX Reader (#70)
  - [x] ODText Reader (#71)
  - [x] RTF Reader (#72)
  - [x] HTML Reader (#80)
- [x] Support of PHP 5.3 (#58 / #77)
- [x] Coverage of UnitTests : 100% (#43)
- [x] Transform the red status in green status on Travis CI (https://travis-ci.org/PHPOffice/PHPWord)

WPS Writer (#69), Daisy XML Writer (#54), and ePub2 Writer (#55) will be implemented later.
